version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3307/fastapi_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --reload

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fastapi_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
